### ISSUE TITLE
forward() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by xiejinglover** [pengzhiliang/MAE-pytorch#36]
Is this a bug?
`        with torch.cuda.amp.autocast():
            outputs = model(images, bool_masked_pos)
            loss = loss_func(input=outputs, target=labels)`
`Traceback (most recent call last):
  File "E:/ImageProject/MAE-OCT/run_mae_pretraining.py", line 264, in <module>
    main(opts)
  File "E:/ImageProject/MAE-OCT/run_mae_pretraining.py", line 238, in main
    normlize_target=args.normlize_target,
  File "E:\ImageProject\MAE-OCT\engine_for_pretraining.py", line 66, in train_one_epoch
    outputs = model(images, bool_masked_pos)
  File "D:\anaconda3\envs\mea\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
`

**Comment by pengzhiliang** [comment]
Hello, have you modified the corresponding code? 
I have not met this problem.
Because the network is normally initialized, the function needs to receive two values: one is the image, and the other is mask. 
https://github.com/pengzhiliang/MAE-pytorch/blob/3546179ac5c4f0b80918b79f68678a42c8719808/modeling_pretrain.py#L93

**Comment by pengzhiliang** [comment]
Please feel free to reopen this issue with more info if you are still stuck in this problem.
Thank you!
